# Generated by Django 4.1 on 2023-04-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_tag_alter_article_category_article_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tag',
            new_name='tags',
        ),
    ]
